const express = require('express');
const fetch = require('node-fetch');
const app = express();
app.use(express.json());

app.post('/generate-image', async (req, res) => {
  const { prompt } = req.body;

  if (!prompt) {
    return res.status(400).json({ error: 'Missing prompt in body' });
  }

  try {
    const response = await fetch('https://stablediffusionapi.com/api/v3/text2img', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        key: process.env.STABLE_DIFFUSION_API_KEY, // your API key from .env
        prompt: prompt,
        // You can add optional parameters here if needed, e.g. width, height, steps etc.
        width: "512",
        height: "512",
        samples: "1",
        num_inference_steps: "20",
        guidance_scale: 7.5,
        seed: null,
        negative_prompt: ""
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      return res.status(response.status).json({ error: 'Stable Diffusion API error', detail: errText });
    }

    const data = await response.json();

    // Return the first generated image URL from output array
    if (data.output && data.output.length > 0) {
      return res.json({ imageUrl: data.output[0] });
    } else {
      return res.status(500).json({ error: 'No image generated by Stable Diffusion API' });
    }
  } catch (error) {
    return res.status(500).json({ error: 'Server error', detail: error.message });
  }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
